#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
# shellcheck source=scripts/lib.sh
. scripts/lib.sh

repo="$(pwd -P)"
bindir="${HOME}/.local/bin"
target="${bindir}/macstral"

mkdir -p "$bindir"

# Generate a thin wrapper that runs THIS repo's justfile from wherever it is
# invoked, so `macstral up` targets your current directory via invocation_directory().
cat > "$target" <<EOF
#!/usr/bin/env bash
# macstral CLI, generated by 'just install-cli'. Runs the macstral justfile from
# wherever you invoke it, so e.g. 'macstral up' targets your current directory.
exec just -f "${repo}/justfile" "\$@"
EOF
chmod +x "$target"

log "installed ${target}"
log "  -> just -f ${repo}/justfile"

case ":${PATH}:" in
  *":${bindir}:"*) : ;;
  *)
    log "note: ${bindir} is not on your PATH."
    # shellcheck disable=SC2016  # literal example shown to the user; must not expand
    log '  add to your shell rc: export PATH="$HOME/.local/bin:$PATH"'
    ;;
esac

log "now: cd <any repo> && macstral up"
